//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingUN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking_log
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idParking { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateEnd { get; set; }
    
        public virtual Parking Parking { get; set; }
        public virtual User User { get; set; }
    }
}
