//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingUN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Parking_log = new HashSet<Parking_log>();
            this.Parking_User = new HashSet<Parking_User>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public long identification { get; set; }
        public string passwordF { get; set; }
    
        public virtual ICollection<Parking_log> Parking_log { get; set; }
        public virtual ICollection<Parking_User> Parking_User { get; set; }
    }
}
